apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-dep
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: web
        image: REGISTRYNAME:BUILDNUMBER
        imagePullPolicy: Always
        ports:
        - name: nginxport
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-dep-svc
spec:
  ports:
  - port: 9999
    nodePort: 32007
    targetPort: nginxport
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
